name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  build_docs:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99'
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-glx
          sudo apt-get install -yqq libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 libopengl0
          /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render -noreset
        name: 'Setup xvfb'
      - run: |
          pip install -r requirements.txt
          pip install --progress-bar off https://github.com/mne-tools/mne-python/zipball/main
        name: 'Install dependencies'
      - run: |
          LD_DEBUG=libs python -c "from PyQt5.QtWidgets import QApplication, QWidget; app = QApplication([])"
        name: 'Check PyQt5'
      - run: |
          which python
          QT_DEBUG_PLUGINS=1 mne sys_info
          python -c "import scooby; print(scooby.Report())"
          python -c "import numpy; numpy.show_config()"
          LIBGL_DEBUG=verbose python -c "import pyvistaqt; pyvistaqt.BackgroundPlotter(show=True)"
        name: 'Check installation'
      - run: sphinx-build -b html doc doc/_build/html
        name: 'Generate HTML docs'
      - name:  Upload generated HTML as artifact
        uses: actions/upload-artifact@v2
        with:
          name: DocHTML
          path: doc/_build/html/
